version: "3.3"

services:
  opigno:
    container_name: opigno
    hostname: opigno
    build: .
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./custom.settings.php:/var/www/html/web/sites/custom.settings.php
    depends_on:
      - mariadb
    restart: always
    networks:
      - web

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=CustomDB_name
      - MYSQL_USER=CustomUserName
      - MYSQL_PASSWORD=YourNONrootPassword
      - MYSQL_ROOT_PASSWORD=YourRootPassword
    volumes:
      - ./data:/var/lib/mysql
    command: [ --max-allowed-packet=67108864 ]
    restart: always
    networks:
      - web

networks:
  web:
